name: novartis-datathon
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - pyarrow
  - scikit-learn
  - matplotlib
  - seaborn
  - pyyaml
  - tqdm
  - lightgbm
  - xgboost
  - catboost
  - pytorch
  - torchvision
  - joblib
  - pip
  - pip:
    - ipykernel
